repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: name-tests-test
        args: [--django]
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.9
        args: [--line-length=88, --target-version=py39]
        types_or: [python, pyi]
        exclude: >-
          (?x)^(
            \.eggs|
            \.git|
            \.mypy_cache|
            \.pytest_cache|
            build|
            dist|
            docs|
            migrations|
            node_modules|
            venv
          )/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile=black, --filter-files, --lines-after-imports=2, --line-length=88]
        types: [python]
        exclude: >-
          (?x)^(
            \.eggs|
            \.git|
            \.mypy_cache|
            \.pytest_cache|
            build|
            dist|
            docs|
            migrations|
            node_modules|
            venv
          )/

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: flake8
        description: "Verificação de estilo e qualidade do código Python"
        entry: flake8
        language: python
        language_version: python3.9
        types: [python]
        exclude: >-
          (?x)^(
            \.eggs|
            \.git|
            \.mypy_cache|
            \.pytest_cache|
            build|
            dist|
            docs|
            migrations|
            node_modules|
            venv
          )/
        additional_dependencies:
          - flake8>=6.1.0
          - flake8-bandit>=4.1.1
          - flake8-bugbear>=23.9.16
          - flake8-comprehensions>=3.14.0
          - flake8-docstrings>=1.7.0
          - flake8-import-order>=0.18.2
          - flake8-print>=5.0.0
          - flake8-quotes>=3.3.2
          - flake8-string-format>=0.3.0
          - pep8-naming>=0.13.3
          - pydocstyle>=6.3.0
        args:
          - --max-line-length=88
          - --ignore=E203,W503
          - --max-complexity=18
          - --docstring-convention=google
          - --import-order-style=google
          - --application-import-names=app,scripts,tests

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: mypy
        description: 'Verificação de tipos estáticos para Python'
        entry: mypy
        language: python
        language_version: python3.9
        types: [python]
        exclude: >-
          (?x)^(
            \.eggs|
            \.git|
            \.mypy_cache|
            \.pytest_cache|
            build|
            dist|
            docs|
            migrations|
            node_modules|
            venv
          )/
        additional_dependencies:
          - types-requests>=2.31.0.1
          - types-python-dateutil>=2.8.19.14
          - types-pyyaml>=6.0.12.11
          - types-setuptools>=68.2.0.0
          - types-pytz>=2023.3.1.0
          - types-six>=1.16.21.8
          - types-urllib3>=1.26.25.14
          - types-psutil>=5.9.5.0
        args:
          - --ignore-missing-imports
          - --disallow-untyped-defs
          - --disallow-incomplete-defs
          - --check-untyped-defs
          - --no-implicit-optional
          - --warn-redundant-casts
          - --warn-unused-ignores
          - --warn-return-any
          - --warn-unreachable
          - --strict-equality
          - --strict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        name: ruff
        description: 'Linter rápido para Python escrito em Rust'
        entry: ruff check --fix --show-fixes
        language: python
        language_version: python3.9
        types: [python]
        exclude: >-
          (?x)^(
            \.eggs|
            \.git|
            \.mypy_cache|
            \.pytest_cache|
            build|
            dist|
            docs|
            migrations|
            node_modules|
            venv
          )/
        args:
          - --fix
          - --unsafe-fixes
          - --show-fixes
          - --target-version=py39
          - --line-length=88
          - --ignore=E203
          - --select=ALL
          - --unfixable=F401,F841
