[project]
name = "langgraph-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bpy",
    "click==8.1.3",
    "elevenlabs>=1.58.1",
    "flask>=3.1.1",
    "logging>=0.4.9.6",
    "mcp[cli]>=1.8.1",
    "tqdm>=4.67.1",
]
