---
# FFmpeg Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg
  namespace: ai-film
  labels:
    app: ffmpeg
    component: video-processing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ffmpeg
  template:
    metadata:
      labels:
        app: ffmpeg
        component: video-processing
    spec:
      containers:
      - name: ffmpeg
        image: jrottenberg/ffmpeg:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 30; done"]
        volumeMounts:
        - name: videos-storage
          mountPath: /videos
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2"
      volumes:
      - name: videos-storage
        persistentVolumeClaim:
          claimName: videos-pvc

---
# FFmpeg Service
apiVersion: v1
kind: Service
metadata:
  name: ffmpeg
  namespace: ai-film
  labels:
    app: ffmpeg
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ffmpeg
